/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fMenuAdmin.java
 *
 * Created on 22/07/2013, 10:19:49 AM
 */

package GUI;

import control.Conexion;
import entidades.Articulo;
import javax.swing.JTable;

/**
 *
 * @author ALUMNO-15
 */
public class fMenuAdmin extends javax.swing.JFrame {
    private Object[][] dtRentas;
    private Object[][] dtVentas;
    private Object[][] dtTransacciones;
    private Object[][] dtArticulos;
    private Object[][] dtVideojuegos;
    private Object[][] dtPeliculas;
    private Object[][] dtClientes;
    private Object[][] dtEmpleados;
    Conexion conex = new Conexion ("localhost","Test Cluster");







    /** Creates new form fMenuAdmin */
    public fMenuAdmin() {
        initComponents();
        bNuevo.setEnabled(false);
        bModificar.setEnabled(false);
        bEliminar.setEnabled(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbEntidad = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPrincipal = new javax.swing.JTable();
        bNuevo = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbEntidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rentas", "Ventas", "Transacciones", "Articulos", "Videojuegos", "Peliculas", "Clientes", "Empleados" }));
        cbEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEntidadActionPerformed(evt);
            }
        });

        tPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tPrincipal);

        bNuevo.setText("Nuevo...");

        bModificar.setText("Modificar");

        bEliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(cbEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEliminar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNuevo)
                    .addComponent(bModificar)
                    .addComponent(bEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEntidadActionPerformed
        // TODO add your handling code here:
        int opc = cbEntidad.getSelectedIndex();
        if ( opc < 3){
            bNuevo.setEnabled(false);
            bModificar.setEnabled(false);
            bEliminar.setEnabled(false);
        }else{
            bNuevo.setEnabled(true);
            bModificar.setEnabled(true);
            bEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_cbEntidadActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fMenuAdmin().setVisible(true);
            }
        });
    }
    
    public void actualizarRentas(){
        String[] columnNames = {"noTransaccion", "articulo", "inicio", "entrega"};
    }
    public void actualizarVentas(){
        String[] columnNames = {"noTransaccion", "articulo", "cantidad", "total"};
    }
    public void actualizarTransacciones(){
        String[] columnNames = {"nombreUsuario", "fecha", "noMembresia", "sucursal", "artTotal", "total"}; 
    }
    public void actualizarArticulos(){
        String[] columnNames = {"clave","precio","descripcion", "tipo"};
        Articulo[] articulo = conex.guardarArticulo();
        dtArticulos = new Object[articulo.length][4];
        for (int i = 0 ;i < articulo.length; i++ ){
            dtArticulos[i][0] = articulo[i].getClave();
            dtArticulos[i][1] = articulo[i].getPrecio();
            dtArticulos[i][2] = articulo[i].getDescripcion();
            dtArticulos[i][3] = articulo[i].getTipo();
        }
        tPrincipal = new JTable(dtArticulos,columnNames);
    }
    public void actualizarVideojuegos(){
        String[] columnNames = {"clave","precio","descripcion", "tipo","titulo", "clasificacion","genero","formato","plataforma","noJugadores","venta"};
        
    }
    public void actualizarPeliculas(){
        String[] columnNames = {"clave","precio","descripcion", "tipo","titulo", "clasificacion","genero","formato","direccion", "año","pais","idioma","subtitulos","venta"};
        
    }
    public void actualizarClientes(){
        String[] columnNames = {"nombre","apellidos","direccion","telefono","tipo","inicio","sucursal"}; 
        
    }
    public void actualizarEmpleados(){
        String[] columnNames = {"nombre","apellidos","direccion","telefono","cargo","inicio","sucursal"}; 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JComboBox cbEntidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tPrincipal;
    // End of variables declaration//GEN-END:variables

}
